// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYrRQHvIKyY9W6kv6-W5vupRiWt1roZRU',
    appId: '1:764368644902:web:385af0159192c84412efe7',
    messagingSenderId: '764368644902',
    projectId: 'banana-munch',
    authDomain: 'banana-munch.firebaseapp.com',
    storageBucket: 'banana-munch.firebasestorage.app',
    measurementId: 'G-5XWSJWJYGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtnnrtVGlnzaVvZwXDF-n8-k-_ErFoubc',
    appId: '1:764368644902:android:10097d6401a79bf112efe7',
    messagingSenderId: '764368644902',
    projectId: 'banana-munch',
    storageBucket: 'banana-munch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiN5vjFso7RSlXH9M7D4zQLMvn39UFDjk',
    appId: '1:764368644902:ios:fb9b2da1e89e05be12efe7',
    messagingSenderId: '764368644902',
    projectId: 'banana-munch',
    storageBucket: 'banana-munch.firebasestorage.app',
    iosBundleId: 'com.example.bananaMunch',
  );
}
